# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get the Eddington Number for Cycling
#'
#' Gets the Eddington number for cycling.
#'
#' The Eddington Number for cycling, \emph{E}, is the maximum number where a
#' cyclist has ridden \emph{E} miles in \emph{E} days. This is not to be
#' confused with the
#' \href{https://en.wikipedia.org/wiki/Eddington_number}{Eddington Number in
#' astrophysics}, \eqn{N_{Edd}}, which represents the number of protons in the
#' observable universe.
#'
#' The Eddington Number for cycling is equivalent to the
#' \href{https://en.wikipedia.org/wiki/H-index}{Hirsch index} for publications.
#'
#' @param rides A vector of mileage, where each element represents a single
#'   ride.
#'
#' @return An integer which is the Eddington cycling number for the
#'   data provided.
#'
#' @seealso \code{\link{E_cum}}, \code{\link{E_sat}}, \code{\link{E_req}}
#'
#' @references http://www2.lowell.edu/users/jch/mtb/e.html
#' @examples
#' # Randomly generate a set of 15 rides
#' rides <- rgamma(15, shape = 2, scale = 10)
#'
#' # View the rides sorted in decreasing order
#' setNames(sort(rides, decreasing = TRUE), seq_along(rides))
#'
#' # Get the Eddington number
#' E_num(rides)
#' @export
E_num <- function(rides) {
    .Call('_eddington_E_num', PACKAGE = 'eddington', rides)
}

#' Calculate the cumulative Eddington number
#'
#' This function is much like \code{\link{E_num}} except it provides
#' a cumulative Eddington number over the vector rather than a single summary
#' number.
#'
#' @inheritParams E_num
#' @seealso \code{\link{E_num}}, \code{\link{E_sat}}, \code{\link{E_req}}
#' @return An integer vector the same length as \code{rides}.
#' @export
E_cum <- function(rides) {
    .Call('_eddington_E_cum', PACKAGE = 'eddington', rides)
}

#' Get the number of rides required to increment to the next Eddington number
#'
#' @inheritParams E_num
#' @seealso \code{\link{E_num}}, \code{\link{E_sat}}, \code{\link{E_cum}}
#' @return A named list with the current Eddington number (\code{E}) and the
#'   number of rides required to increment by one (\code{req}).
#' @export
E_req <- function(rides) {
    .Call('_eddington_E_req', PACKAGE = 'eddington', rides)
}

