[package]
name = "eddington"
version = "0.1.0"
authors = ["pegeler <paulegeler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
